### ISSUE TITLE
layouts

### ISSUE THREAD

**Issue by mgood7123** [randrew/layout#18]
how can custom layouts be achieved?

for example, a grid with AxB columns/rows

or a LinearLayout https://developer.android.com/guide/topics/ui/layout/linear.html

or even ConstraintLayout https://developer.android.com/develop/ui/views/layout/constraint-layout

**Comment by randrew** [comment]
layout.h does the `LinearLayout` by default. That's how it usually works.

layout.h doesn't have a 'grid' mode. If you need a grid, you can do it with custom code. Grids are usually simple and don't require complex layout logic, since all you really need to know is the largest size of each cell in each row and column.

layout.h isn't a constraint solver or constraint-based system and doesn't do constraint layouts.
